@E_Commerce.Web_HostAddress = http://localhost:5133

GET {{E_Commerce.Web_HostAddress}}/weatherforecast/
Accept: application/json

### Get Products

GET {{E_Commerce.Web_HostAddress}}/api/Products

### Get Product by Id
@id = 10
GET {{E_Commerce.Web_HostAddress}}/api/Products/{{id}}
